### ISSUE TITLE
Deploy on Heroku Docs

### ISSUE THREAD

**Issue by leonanluppi** [pemberton-rank/react-shopify-app#22]
Hi,

Any docs for heroku deploy?

**Comment by mib32** [comment]
Hi!
No, we do not support heroku yet. However there's Amazon EC2 instructions you can find in PRODUCTION_SETUP.md

I'd recommend for you to read this, very well written blog post by heroku worker, and you actually can easily adapt react-shopify-app for that - https://blog.heroku.com/a-rock-solid-modern-web-stack?c=7013A000000ZGTBQA4&utm_campaign=Newsletter_May_2018&utm_medium=email&utm_source=newsletter&utm_content=blog&utm_term=web_stack
